export const theme = {
    mainColor: "#FFFFFF",
    accentColor: "#F66B0E",
    accentTextColor: "#FF0000",
    genresColor: "#F66B0E",
    cardsShadowColor: "#1e0d02",
    altColor: "#B2B1B9",
    mainBG: "#201914a3",
    accentBG: "#1f1f1f",
    navigateBG: "#201914a3",
    altBG: "#1e1e1e",
    lightBG: "#2B2B2B",
    transition: "250ms ease-in-out",
    headerHeight: "52px",
    footerHeight: "0px",
    mainFF: "Comfortaa",
    cardBGColor: "#FFFFFF",
    buttonBG: "#C0C0C0",
    // mainBG: "#EFEFEF",
};
